export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const AGREGAR_PRODUCTO_EXITO = "AGREGAR_PRODUCTO_EXITO";
export const AGREGAR_PRODUCTO_ERROR = "AGREGAR_PRODUCTO_ERROR";

export const OBTENER_PRODUCTOS = "OBTENER_PRODUCTOS";
export const OBTENER_PRODUCTOS_EXITOSO = "OBTENER_PRODUCTOS_EXITOSO";
export const OBTENER_PRODUCTOS_ERROR = "OBTENER_PRODUCTOS_ERROR";

export const OBTENER_PRODUCTO_ELIMINAR = "OBTENER_PRODUCTO_ELIMINAR";
export const PRODUCTO_ELIMINAR_EXITOSO = "PRODUCTO_ELIMINAR_EXITOSO";
export const PRODUCTO_ELIMINAR_ERROR = "PRODUCTO_ELIMINAR_ERROR";

export const OBTENER_PRODUCTO_EDITAR = "OBTENER_PRODUCTO_EDITAR";
export const PRODUCTO_EDITAR_EXITOSO = "PRODUCTO_EDITAR_EXITOSO";
export const PRODUCTO_EDITAR_ERROR = "PRODUCTO_EDITAR_ERROR";

export const RESET_STATE = "RESET_STATE";

export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";

